# Generated by Django 4.2.27 on 2026-01-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConvention',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('sent_to_odoo', 'Envoyée à Odoo')], default='draft', max_length=30)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('odoo_id', models.IntegerField(blank=True, null=True)),
                ('sent_to_odoo_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project')),
            ],
            options={
                'verbose_name': 'historical Convention',
                'verbose_name_plural': 'historical Conventions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('sent_to_odoo', 'Envoyée à Odoo')], default='draft', max_length=30)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('odoo_id', models.IntegerField(blank=True, null=True)),
                ('sent_to_odoo_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convention', to='projects.project')),
            ],
            options={
                'verbose_name': 'Convention',
                'verbose_name_plural': 'Conventions',
                'indexes': [models.Index(fields=['status'], name='conventions_status_bdf327_idx'), models.Index(fields=['reference'], name='conventions_referen_02ac0b_idx'), models.Index(fields=['odoo_id'], name='conventions_odoo_id_431964_idx')],
            },
        ),
    ]
