# Generated by Django 4.2.28 on 2026-02-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalconvention',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
