# Generated by Django 4.2.28 on 2026-03-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0018_filiere_nombre_max_budgets'),
        ('conventions', '0002_alter_historicalconvention_history_change_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='budgets.infosbudget', verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='convention',
            name='date_signature',
            field=models.DateField(blank=True, null=True, verbose_name='Date de signature'),
        ),
        migrations.AddField(
            model_name='historicalconvention',
            name='budget',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='budgets.infosbudget', verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='historicalconvention',
            name='date_signature',
            field=models.DateField(blank=True, null=True, verbose_name='Date de signature'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='reference',
            field=models.CharField(max_length=100, unique=True, verbose_name='Numéro de la convention'),
        ),
        migrations.AlterField(
            model_name='historicalconvention',
            name='reference',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Numéro de la convention'),
        ),
    ]
