# Generated by Django 4.2.28 on 2026-03-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0018_filiere_nombre_max_budgets'),
        ('conventions', '0003_add_budget_date_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='budget',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convention', to='budgets.infosbudget', verbose_name='Budget'),
        ),
    ]
