# Generated by Django 4.2.28 on 2026-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0004_budget_onetone'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='dure_convention',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de la convention (en mois)'),
        ),
        migrations.AddField(
            model_name='historicalconvention',
            name='dure_convention',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de la convention (en mois)'),
        ),
    ]
