# Generated by Django 4.2.27 on 2026-01-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('locations', models.CharField(blank=True, max_length=255)),
                ('approved_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('under_review', 'En revue'), ('validated', 'Validé'), ('locked', 'Verrouillé')], default='draft', max_length=30)),
                ('ready_for_convention', models.BooleanField(default=False)),
                ('validated_by_admin', models.BooleanField(default=False)),
                ('admin_comment', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gg_application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integrations.goodgrantsapplication')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operators.operator')),
            ],
            options={
                'verbose_name': 'historical Projet',
                'verbose_name_plural': 'historical Projets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('locations', models.CharField(blank=True, max_length=255)),
                ('approved_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('under_review', 'En revue'), ('validated', 'Validé'), ('locked', 'Verrouillé')], default='draft', max_length=30)),
                ('ready_for_convention', models.BooleanField(default=False)),
                ('validated_by_admin', models.BooleanField(default=False)),
                ('admin_comment', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gg_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='integrations.goodgrantsapplication')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='operators.operator')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'indexes': [models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'), models.Index(fields=['ready_for_convention'], name='projects_pr_ready_f_86706f_idx')],
            },
        ),
    ]
