# Generated by Django 4.2.27 on 2026-02-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_historicalappelaprojet_appelaprojet'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelaprojet',
            name='actif_manuellement',
            field=models.BooleanField(default=False, help_text="Cochez pour forcer l'activation de l'appel, même en dehors des dates prévues.", verbose_name='Activé manuellement'),
        ),
        migrations.AddField(
            model_name='historicalappelaprojet',
            name='actif_manuellement',
            field=models.BooleanField(default=False, help_text="Cochez pour forcer l'activation de l'appel, même en dehors des dates prévues.", verbose_name='Activé manuellement'),
        ),
    ]
