# Generated by Django 4.2.28 on 2026-02-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_suppression_actif_manuellement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalappelaprojet',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
