# Generated by Django 4.2.27 on 2026-01-30 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIntegrationEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('system', models.CharField(choices=[('goodgrants', 'GoodGrants'), ('odoo', 'Odoo')], max_length=50)),
                ('direction', models.CharField(choices=[('in', 'Entrant'), ('out', 'Sortant')], max_length=10)),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('processed', 'Traité'), ('failed', 'Échec')], default='received', max_length=20)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Événement intégration',
                'verbose_name_plural': 'historical Événements intégrations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('goodgrants', 'GoodGrants'), ('odoo', 'Odoo')], max_length=50)),
                ('direction', models.CharField(choices=[('in', 'Entrant'), ('out', 'Sortant')], max_length=10)),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('processed', 'Traité'), ('failed', 'Échec')], default='received', max_length=20)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement intégration',
                'verbose_name_plural': 'Événements intégrations',
                'indexes': [models.Index(fields=['system', 'direction', 'status'], name='audits_inte_system_065d7e_idx'), models.Index(fields=['correlation_id'], name='audits_inte_correla_2b1696_idx'), models.Index(fields=['external_id'], name='audits_inte_externa_fbbc4a_idx'), models.Index(fields=['created_at'], name='audits_inte_created_151634_idx')],
            },
        ),
    ]
