# Generated by Django 4.2.28 on 2026-02-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_historicalauditlog_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalauditlog',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalintegrationevent',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
