# Generated by Django 4.2.27 on 2026-02-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_remove_operator_operators_o_name_362a57_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperator',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='last_synced_at',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='website',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='last_synced_at',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='website',
        ),
    ]
