# Generated by Django 4.2.28 on 2026-02-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_remove_historicaloperator_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperator',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
