# Generated by Django 4.2.27 on 2026-02-05 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('cout_total_groupe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('co_financement_groupe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subvention_groupe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalInfosBudget',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('operateur', models.CharField(max_length=255, verbose_name='Opérateur ou Consortium')),
                ('titre_projet', models.TextField(verbose_name='Titre du projet')),
                ('filiere', models.CharField(max_length=255, verbose_name='Filière de formation')),
                ('metiers', models.CharField(max_length=255, verbose_name='Métiers')),
                ('localite', models.CharField(max_length=255, verbose_name='Localité')),
                ('total_apprenants', models.PositiveIntegerField(default=1, verbose_name='Effectif total apprenants')),
                ('nombre_sessions', models.PositiveIntegerField(default=1, verbose_name='Nombre de sessions')),
                ('cout_total_global', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('co_financement_global', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subvention_demandee_globale', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cout_par_apprenant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical infos budget',
                'verbose_name_plural': 'historical infos budgets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InfosBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(max_length=255, verbose_name='Opérateur ou Consortium')),
                ('titre_projet', models.TextField(verbose_name='Titre du projet')),
                ('filiere', models.CharField(max_length=255, verbose_name='Filière de formation')),
                ('metiers', models.CharField(max_length=255, verbose_name='Métiers')),
                ('localite', models.CharField(max_length=255, verbose_name='Localité')),
                ('total_apprenants', models.PositiveIntegerField(default=1, verbose_name='Effectif total apprenants')),
                ('nombre_sessions', models.PositiveIntegerField(default=1, verbose_name='Nombre de sessions')),
                ('cout_total_global', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('co_financement_global', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subvention_demandee_globale', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cout_par_apprenant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='LigneBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=255)),
                ('cout_total_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('co_financement_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subvention_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='SectionBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('libelle', models.CharField(max_length=255)),
                ('cout_total_section', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('co_financement_section', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subvention_section', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='budgets.infosbudget')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SousLigneArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('unite', models.CharField(max_length=50)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('co_financement', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cout_total_article', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_demande_article', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='budgets.groupearticle')),
            ],
        ),
        migrations.RemoveField(
            model_name='budgetsubline',
            name='line',
        ),
        migrations.RemoveField(
            model_name='historicalbudgetline',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='historicalbudgetline',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbudgetline',
            name='section',
        ),
        migrations.RemoveField(
            model_name='historicalbudgetsection',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbudgetsubline',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbudgetsubline',
            name='line',
        ),
        migrations.DeleteModel(
            name='BudgetLine',
        ),
        migrations.DeleteModel(
            name='BudgetSection',
        ),
        migrations.DeleteModel(
            name='BudgetSubLine',
        ),
        migrations.DeleteModel(
            name='HistoricalBudgetLine',
        ),
        migrations.DeleteModel(
            name='HistoricalBudgetSection',
        ),
        migrations.DeleteModel(
            name='HistoricalBudgetSubLine',
        ),
        migrations.AddField(
            model_name='lignebudgetaire',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='budgets.sectionbudgetaire'),
        ),
        migrations.AddField(
            model_name='groupearticle',
            name='ligne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='budgets.lignebudgetaire'),
        ),
    ]
