# Generated by Django 4.2.27 on 2026-02-07 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_ajout_champs_calcul_synthese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinfosbudget',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Identifiant unique'),
        ),
        migrations.AlterField(
            model_name='infosbudget',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant unique'),
        ),
    ]
