# Generated by Django 4.2.27 on 2026-02-07 17:33

from django.db import migrations


def update_existing_budgets(apps, schema_editor):
    """Met à jour les budgets existants avec la nouvelle structure"""
    SectionBudgetaire = apps.get_model('budgets', 'SectionBudgetaire')
    LigneBudgetaire = apps.get_model('budgets', 'LigneBudgetaire')
    GroupeArticle = apps.get_model('budgets', 'GroupeArticle')

    # Mettre à jour les sections A
    for section in SectionBudgetaire.objects.filter(code='A'):
        section.libelle = 'Formation'
        section.save()

    # Mettre à jour les sections B
    for section in SectionBudgetaire.objects.filter(code='B'):
        section.libelle = 'Accompagnement à l\'insertion'
        section.save()

    # Mettre à jour A.1
    for ligne in LigneBudgetaire.objects.filter(code='A.1'):
        ligne.libelle = 'Matières d\'œuvre'
        ligne.save()

    # Fusionner B.1 et B.2 en une seule ligne B
    for section in SectionBudgetaire.objects.filter(code='B'):
        # Supprimer les anciennes lignes B.1 et B.2 si elles existent
        LigneBudgetaire.objects.filter(section=section, code__in=['B.1', 'B.2']).delete()

        # Créer ou récupérer la ligne B unique
        ligne_b, created = LigneBudgetaire.objects.get_or_create(
            section=section,
            code='B',
            defaults={'libelle': 'Accompagnement à l\'insertion'}
        )

        # S'assurer qu'il y a au moins un groupe
        if not GroupeArticle.objects.filter(ligne=ligne_b).exists():
            GroupeArticle.objects.create(
                libelle='Activités d\'appui à l\'insertion',
                ligne=ligne_b
            )


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_alter_historicalinfosbudget_uuid_and_more'),
    ]

    operations = [
        migrations.RunPython(update_existing_budgets, reverse_code=migrations.RunPython.noop),
    ]
