# Generated by Django 4.2.27 on 2026-02-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_update_existing_budgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinfosbudget',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation"),
        ),
        migrations.AddField(
            model_name='historicalinfosbudget',
            name='date_autorisation_modification',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'autorisation de modification"),
        ),
        migrations.AddField(
            model_name='historicalinfosbudget',
            name='date_demande_modification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de demande de modification'),
        ),
        migrations.AddField(
            model_name='historicalinfosbudget',
            name='date_soumission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission'),
        ),
        migrations.AddField(
            model_name='historicalinfosbudget',
            name='motif_demande_modification',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de la demande de modification'),
        ),
        migrations.AddField(
            model_name='historicalinfosbudget',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('demande_modification', 'Demande de modification'), ('modification_autorisee', 'Modification autorisée'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='brouillon', max_length=30, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='infosbudget',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation"),
        ),
        migrations.AddField(
            model_name='infosbudget',
            name='date_autorisation_modification',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'autorisation de modification"),
        ),
        migrations.AddField(
            model_name='infosbudget',
            name='date_demande_modification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de demande de modification'),
        ),
        migrations.AddField(
            model_name='infosbudget',
            name='date_soumission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission'),
        ),
        migrations.AddField(
            model_name='infosbudget',
            name='motif_demande_modification',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de la demande de modification'),
        ),
        migrations.AddField(
            model_name='infosbudget',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('demande_modification', 'Demande de modification'), ('modification_autorisee', 'Modification autorisée'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='brouillon', max_length=30, verbose_name='Statut'),
        ),
    ]
