# Generated by Django 4.2.27 on 2026-02-09 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_historicalappelaprojet_appelaprojet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0009_historicalinfosbudget_date_approbation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinfosbudget',
            name='appel_a_projet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.appelaprojet', verbose_name='Appel à projet'),
        ),
        migrations.AddField(
            model_name='infosbudget',
            name='appel_a_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='projects.appelaprojet', verbose_name='Appel à projet'),
        ),
        migrations.AlterField(
            model_name='infosbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
