# Generated by Django 4.2.28 on 2026-02-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0013_suppression_cout_total_soumis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
            ],
        ),
    ]
