# Generated by Django 4.2.28 on 2026-02-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0016_metier_filiere_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinfosbudget',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalinfosbudget',
            name='operateur',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Opérateur ou Consortium'),
        ),
        migrations.AlterField(
            model_name='infosbudget',
            name='operateur',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Opérateur ou Consortium'),
        ),
    ]
