# Generated by Django 4.2.28 on 2026-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0017_alter_historicalinfosbudget_history_change_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='nombre_max_budgets',
            field=models.PositiveIntegerField(default=2, verbose_name='Nombre max de budgets par opérateur'),
        ),
    ]
