# Generated by Django 4.2.28 on 2026-03-24 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0018_filiere_nombre_max_budgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinfosbudget',
            name='total_apprenants',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(50, message="Le nombre d'apprenants doit être d'au moins 50.")], verbose_name='Effectif total apprenants'),
        ),
        migrations.AlterField(
            model_name='infosbudget',
            name='total_apprenants',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(50, message="Le nombre d'apprenants doit être d'au moins 50.")], verbose_name='Effectif total apprenants'),
        ),
    ]
